/* eslint-disable max-len */
// GENERATED by scripts/build-drop-email-assets.mjs - do not edit by hand.
// Each drop picture's source name mapped to its content-hashed, site-
// relative path, so a changed picture is always a new address.

export const DROP_ASSETS: Readonly<Record<string, Readonly<Record<string, string>>>> = {
  "halloween-2026": {
    "candy_corn.png": "images/drops/halloween-2026/candy_corn-c6883bfadf99.png",
    "chocolate_bar.png": "images/drops/halloween-2026/chocolate_bar-f64d3a1bea7b.png",
    "cobweb-left.png": "images/drops/halloween-2026/cobweb-left-9701018c0bd8.png",
    "cobweb-right.png": "images/drops/halloween-2026/cobweb-right-9848ce04fb25.png",
    "ember_trainers.png": "images/drops/halloween-2026/ember_trainers-2df01cc2ba26.png",
    "ghost_sheet.png": "images/drops/halloween-2026/ghost_sheet-3d3f21bae2ee.png",
    "glow_trainers.png": "images/drops/halloween-2026/glow_trainers-7c7d45595d47.png",
    "haunted-band.jpg": "images/drops/halloween-2026/haunted-band-206d7d348b96.jpg",
    "pumpkin_classic.png": "images/drops/halloween-2026/pumpkin_classic-b848621b96b8.png",
    "pumpkin_ghost.png": "images/drops/halloween-2026/pumpkin_ghost-efca9de19b97.png",
    "pumpkin_giant.png": "images/drops/halloween-2026/pumpkin_giant-b342c8004a96.png",
    "pumpkin_giant_lantern.png": "images/drops/halloween-2026/pumpkin_giant_lantern-f083acd275f7.png",
    "pumpkin_head.png": "images/drops/halloween-2026/pumpkin_head-65d4ba6a0c01.png",
    "pumpkin_heirloom.png": "images/drops/halloween-2026/pumpkin_heirloom-2481d3bc4ad6.png",
    "pumpkin_lantern.png": "images/drops/halloween-2026/pumpkin_lantern-ec35dbd6803d.png",
    "pumpkin_midnight.png": "images/drops/halloween-2026/pumpkin_midnight-4f1375193e68.png",
    "witch_hat.png": "images/drops/halloween-2026/witch_hat-c1391cca6b3f.png",
    "witching_shorts.png": "images/drops/halloween-2026/witching_shorts-2ef57ab2e68f.png",
  },
};
